services:

  events:
    build: ./users_events_service
    command: npm run start:dev
    env_file:
      - ./users_events_service/.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    volumes:
      - ./users_events_service:/usr/src/app
      - ./users_events_service/node_modules:/usr/src/app/node_modules
    networks:
      - internal

  notifications:
    build: ./email_notification_service
    command: npm run start:dev
    env_file:
      - ./email_notification_service/.env
    ports:
      - '3001:3001'
    volumes:
      - ./email_notification_service:/usr/src/app
      - ./email_notification_service/node_modules:/usr/src/app/node_modules
    networks:
      - internal

  postgres:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:6.2-alpine
    ports:
      - ${REDIS_PORT}:6379
    restart: always
    networks:
      - internal
    volumes:  
      - cache_data:/data  

networks:
  internal:
    driver: bridge

volumes:
  database_data:
  cache_data:
