services:

  events:
    build: ./users_events_service
    command: npm run start:dev
    env_file:
      - ./users_events_service/.env
    ports:
      - '3000:3000'
    depends_on:
      - database
    volumes:
      - ./users_events_service:/usr/src/app
      - ./users_events_service/node_modules:/usr/src/app/node_modules
    networks:
      - internal

  notifications:
    build: ./email_notification_service
    command: npm run start:dev
    env_file:
      - ./email_notification_service/.env
    ports:
      - '3001:3001'
    volumes:
      - ./email_notification_service:/usr/src/app
      - ./email_notification_service/node_modules:/usr/src/app/node_modules
    networks:
      - internal

  database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - internal


networks:
  internal:

volumes:
  database_data:
